version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
